### ISSUE TITLE
CI upgrades not initializing upstream repo correctly

### ISSUE THREAD

**Issue by aq17** [pulumi/upgrade-provider#112]
The last week or so, most upgrades have been failing with a similar issue
https://github.com/pulumi/pulumi-gitlab/commit/74bb1cc35db6178e918cf9a1b5b3f94739025d99/checks

`go: gitlab.com/gitlab-org/terraform-provider-gitlab@v0.0.0 (replaced by ../upstream): reading ../upstream/go.mod: open /home/runner/work/pulumi-gitlab/pulumi-gitlab/upstream/go.mod: no such file or directory`

where it appears the upstream directory is not being initialized/ is empty, causing the upgrade to fail.

Re-running the upgrade locally succeeds (i.e. https://github.com/pulumi/pulumi-gitlab/pull/316)

**Comment by mikhailshilkov** [comment]
@aq17 It looks like Azure failed because of this, let's get this fix prioritised?
https://github.com/pulumi/pulumi-azure/actions/runs/5617365095/job/15221349196#step:3:1470
