### ISSUE TITLE
Upgrade-provider doesn't support multiple tags on the same SHA

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/upgrade-provider#120]
### What happened?

Automatic upgrade of pulumi-rancher2 [failed ](https://github.com/pulumi/pulumi-rancher2/actions/runs/5651615304/job/15334612232#step:3:815) because a git SHA could not be found.

### Expected Behavior

The upgrader should find the corresponding SHA of a git tag.

### Steps to reproduce

This occurred because both the `v3.1.0-rc6` and `v3.1.0` tags were set on the exact same git SHA.

[This line](https://github.com/pulumi/upgrade-provider/blob/main/upgrade/steps-helpers.go#L325) maps git SHA to git tag, using the SHA as a map key.

Since map keys must be unique, this can result in an overwrite, removing the desired sha/tag pair from the lookup map, resulting in a failed upgrade.

This is a bit hard to reproduce, but I imagine we can hard-code "v3.1.0" somewhere in this tool, and run it against Rancher.
We should certainly write a unit test that captures this scenario.

### Output of `pulumi about`

n/a

### Additional context

Not sure what the correct approach is here. We can try to remove `rc` tags from the list, but that only removes one possible source of key conflict.
I imagine a more involved rewrite that maps tags to SHA rather than vice versa is called for here, since tags must be unique.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Thanks for writing such a detailed bug report!

**Comment by guineveresaenger** [comment]
I think this was fixed in #153.
