### ISSUE TITLE
allow customizing the pr assignee

### ISSUE THREAD

**Issue by omercnet** [pulumi/upgrade-provider#121]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
When running this in a github action the GITHUB_TOKEN belongs to @github-actions[bot], so using `@me` as the assignee fails, allowing to customize the assignee would help mitigate that

**Comment by rquitales** [comment]
@omercnet Thanks for reporting this enhancement and supplying a PR to address this. We look forward to working with you on merging this in.
