### ISSUE TITLE
does not fail on error

### ISSUE THREAD

**Issue by omercnet** [pulumi/upgrade-provider#130]
### What happened?

running the action with a malformed config fails the command but the action does not fail

### Expected Behavior

action should fail, which would result in a notification to the repo admin that something's broken

### Steps to reproduce

see https://github.com/pulumiverse/pulumi-vercel/pull/44 and all the runs in https://github.com/pulumiverse/pulumi-vercel/actions/runs/6001806781/job/16276798111 that were successful although the action failed

### Output of `pulumi about`

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
I'm going to pin this until it is fixed, since it is a pretty serious foot gun.
