### ISSUE TITLE
fails when no upgrade is required

### ISSUE THREAD

**Issue by omercnet** [pulumi/upgrade-provider#132]
### What happened?

provider exits with non-zero status when no upgrade is required, causing a scheduled github action to fail and send alerts

```
 Planning Provider Update: current upstream version 0.15.1 is greater than/ equal to the target version 0.15.1
```

### Expected Behavior

should exit with 0 when no action is required

### Steps to reproduce

https://github.com/pulumiverse/pulumi-vercel/actions/runs/6062588666/job/16448996484

### Output of `pulumi about`

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by omercnet** [comment]
https://github.com/pulumi/upgrade-provider/blob/b7f53adf00f1c4f12686a56ba7e0bd08c967be8f/upgrade/upgrade-provider.go#L105

shouldn't be `Error`

**Comment by mikhailshilkov** [comment]
Sounds good @omercnet. Do you want to try to open a PR to fix that?

**Comment by omercnet** [comment]
fixed by https://github.com/pulumi/upgrade-provider/commit/7101316c7fc5fcdb2d47aa4c960badb909d9a17c#diff-0ec6a36f0bf0306c7b5960cc9932cb0a28a3f26c027a208c161c10828255e3e1

**Comment by mikhailshilkov** [comment]
Fixed by https://github.com/pulumi/upgrade-provider/pull/136
