### ISSUE TITLE
`upgrade-provider` does not update `sdk/go.mod` pulumi version

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/upgrade-provider#134]
### What happened?

During a routine upgrade, I kept getting "no required module" errors. Running the upgrade manually, I isolated the error to the build go sdk step.

### Expected Behavior

Successful build of the go SDK

### Steps to reproduce

Set [this sample sdk.go.mod's pulumi version](https://github.com/pulumi/pulumi-artifactory/blob/main/sdk/go.mod#L7) to a laughably low Pulumi version, such as `v3.36.0`

Run `make build_go`

Observe errors such as

```
go/artifactory/accessToken.go:13:2: no required module provides package github.com/pulumi/pulumi/sdk/v3/go/pulumix; to add it:
	go get github.com/pulumi/pulumi/sdk/v3/go/pulumix
go/artifactory/accessToken.go:13:2: no required module provides package github.com/pulumi/pulumi/sdk/v3/go/pulumix; to add it:
	go get github.com/pulumi/pulumi/sdk/v3/go/pulumix
make: *** [build_go] Error 1
```

### Output of `pulumi about`

```
CLI          
Version      3.81.0
Go Version   go1.21.1
Go Compiler  gc
```

### Additional context

I believe not auto-updating the `sdk/go.mod` was an oversight in the tool that we should correct.

We should always update the SDK's pulumi version to latest as well.

It is, unfortunately, [missing from the full playbook as well.](https://github.com/pulumi/platform-providers-team/blob/main/playbooks/tf-provider-updating.md)

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
This might be a P1. It's blocking automated weekly Pulumi update jobs across every single provider.  We'd need to figure out how to mass-update this.

**Comment by mikhailshilkov** [comment]
@guineveresaenger Do you want to take this issue? It sounds like it's worth prioritizing.
