### ISSUE TITLE
Fix "Author identity unknown" failures

### ISSUE THREAD

**Issue by mjeffryes** [pulumi/upgrade-provider#144]
Eg. https://github.com/pulumi/pulumi-postgresql/actions/runs/6138043392/job/16770521893

Other instances:
- https://github.com/pulumi/pulumi-hcloud/actions/runs/6387534715/job/17336020835

**Comment by t0yv0** [comment]
I'm running into this in GCP also, that didn't self-upgrade the bridge. I'll try to upgrade the bridge by hand in GCP.
