### ISSUE TITLE
Automate release after provider upgrade merged (1 eng week)

### ISSUE THREAD

**Issue by mjeffryes** [pulumi/upgrade-provider#148]
The current process requires an engineer to wait for CI to finish after merging an upgrade and then manually initiate a release. This is frequently forgotten and incurs a fair amount of switching overhead for the person doing the upgrade+release. 

We propose to add an automation that allows the person merging the upgrade PR to enqueue a release that will run once the change has built successfully on master. One possible implementation could be a slash-command style comment on the PR that indicates the version increment (major/minor/patch), which is read when the master build completes to generate a message to releasebot.

**Comment by mikhailshilkov** [comment]
Is this the same as https://github.com/pulumi/home/issues/3071?

**Comment by mjeffryes** [comment]
> Is this the same as [pulumi/home#3071](https://github.com/pulumi/home/issues/3071)?

yes

**Comment by mikhailshilkov** [comment]
Which one do we close as a dupe?

**Comment by mjeffryes** [comment]
https://github.com/pulumi/home/issues/3071 is more articulate let's use that one.
