### ISSUE TITLE
Does not update examples/go.mod pulumi/pkg reference

### ISSUE THREAD

**Issue by t0yv0** [pulumi/upgrade-provider#149]
### What happened?

https://github.com/pulumi/pulumi-gcp/pull/1198

After using upgrade-provider I got diverging version references pulumi/pkg at one version and pulumi/sdk at another, in examples/go.mod. This fails the PR.

### Expected Behavior

Matching version references.

### Steps to reproduce

See above.

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
This should have been fixed in #152. Please reopen if that is not the case.
