### ISSUE TITLE
Bridge upgrade fails on the Pulumi-external provider

### ISSUE THREAD

**Issue by t0yv0** [pulumi/upgrade-provider#161]
### What happened?

```
~/code/upgrade-provider/upgrade-provider pulumi/pulumi-http --kind bridge                                                                                                                                   ~/code/pulumi-external
---- Setting Up Environment ----
- ✓ GOWORK="off": done
- ✓ PULUMI_MISSING_DOCS_ERROR="true": done
- ✓ PULUMI_CONVERT_EXAMPLES_CACHE_DIR="": done
---- Discovering Repository ----
- Ensure 'github.com/pulumi/pulumi-http'
  - ✓ Expected Location: /Users/t0yv0/go/src/github.com/pulumi/pulumi-http
  - ✓ Downloading: skipped - already exists
  - ✓ Validating: done
- pull default branch
  - ✓ /usr/bin/git ls-remote --heads origin: done
  - ✓ finding default branch: main
  - ✓ /usr/bin/git fetch: done
  - ✓ /usr/bin/git checkout main: done
  - ✓ /usr/bin/git pull origin: done
- X Repo kind: go.mod: could not find upstream 'terraform-provider-external' in go.mod

```

### Example

See above

### Output of `pulumi about`

N/A

### Additional context

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
I can probably proceed with the upgrade locally.

**Comment by mikhailshilkov** [comment]
@t0yv0 Can you add a summary of why? Is it a tool problem or a mis-configuration in pulumi-external?

**Comment by t0yv0** [comment]
I can't find these logs anymore. I've resolved Pulumi-external by hand, and the only logs I can find is https://github.com/pulumi/pulumi-external/actions/runs/6166004177/job/16734763878#step:3:648 that's been solved already in Pulumi-provider. Closing for now.
