### ISSUE TITLE
Signalfx major upgrade left provider out of sync with ci-mgmt

### ISSUE THREAD

**Issue by t0yv0** [pulumi/upgrade-provider#165]
### What happened?

This update https://github.com/pulumi/pulumi-signalfx/pull/272

left it on v7 vs v6.

This in turn caused https://github.com/pulumi/ci-mgmt/issues/622 p1

This is pretty unfortunate. What's the plan here, should we move the major version number out of ci-mgmt and into repo? That feels like something that could really help here.

### Example

N/A

### Output of `pulumi about`

N/A

### Additional context

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
I believe this is not currently handled in the upgrade tool. Do you think it should be? Or should we move this issue to ci-mgmt?

**Comment by t0yv0** [comment]
Yeah I'm open ideas where to handle this; mostly filing to rethink later. The current process is *broken* because one automation breaks another automation, by design. This needs fixing. 

Perhaps one fix would be to move major version out of ci-mgmt and into a config file in each provider repo.

**Comment by iwahbe** [comment]
Since this issue was opened, the major version of the provider is now stored in `.ci-mgmt.yaml` in the provider. It is now conceivable that `upgrade-provider` can do the major version in 1 PR.

**Comment by t0yv0** [comment]
Yes, I can confirm using .ci-mgmt.yaml to move around in pulumi-gcp with great ease. I consider this fixed.
