### ISSUE TITLE
Upgrade bridge: `make upstream` failure: Reading upstream go.mod: no such file or directory

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/upgrade-provider#172]
### What happened?

Upgrading the bridge for `auth0` and `external` failed, both with an error message about an `upstream` go.mod file not existing.

### Example

This happened in CI: https://github.com/pulumi/pulumi-auth0/actions/runs/6387504018/job/17335940476

```
go: github.com/auth0/terraform-provider-auth0@v0.50.2 (replaced by ../upstream): reading ../upstream/go.mod: open /home/runner/work/pulumi-auth0/pulumi-auth0/upstream/go.mod: no such file or directory
```

### Output of `pulumi about`

n/a

### Additional context

https://github.com/pulumi/pulumi-external/actions/runs/6387527214/job/17336002314#step:3:1178 - same failure

Possibly related: https://github.com/pulumi/upgrade-provider/issues/163

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
cc @iwahbe to take a look

**Comment by iwahbe** [comment]
Looks like https://github.com/pulumi/pulumi-external/issues/23 is caused by the same issue.
