### ISSUE TITLE
"provider" mode does not work

### ISSUE THREAD

**Issue by vavsab** [pulumi/upgrade-provider#179]
### What happened?

After [context refactor pr](https://github.com/pulumi/upgrade-provider/pull/174) I cannot upgrade in provider mode anymore.
Checked that the problem still exists in the [latest commit](https://github.com/pulumi/upgrade-provider/commit/4791ea6890c04b8540efe19161ec13e09085b495)
Also checked [one commit before the PR](https://github.com/pulumi/upgrade-provider/pull/171) - it works as expected.

Could you please check what the magic happed there? Why do I see pending update and then it's ignored. I tried to dig in the code... looks like it's some references bug.

![image](https://github.com/pulumi/upgrade-provider/assets/10233442/c00b3d05-bbe1-47a0-a927-7eb5ac9c630d)

cc: @iwahbe 

### Example

https://github.com/pulumiverse/pulumi-zitadel/actions/runs/6546386505/job/17776740556#step:10:27

### Output of `pulumi about`

It's inside of CI. I'm using this action to setup the latest pulumi 
https://github.com/pulumiverse/pulumi-zitadel/blob/6bb78c4b2a3b08a5fd2437ab67f18a7da684491a/.github/workflows/upgrade-provider.yml#L28

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hi @vavsab. Thanks for opening this issue. We noticed that ourselves as well. There will be a fix out shortly.

**Comment by vavsab** [comment]
Thank you for fixing it so quickly!
