### ISSUE TITLE
Do not upgrade pulumi/pkg and pulumi/sdk ahead of the bridge

### ISSUE THREAD

**Issue by t0yv0** [pulumi/upgrade-provider#184]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

This is contrary to prior requests originating from me, but I believe at the moment our deployment pipeline would benefit from never upgrading pulumi/pkg references (which installs codegen fixes) ahead of what was tested in pulumi-terraform-bridge. This makes sure additional bridge release checks such as [this](https://github.com/pulumi/pulumi-terraform-bridge/actions/workflows/update-providers-test.yml) qualify the codegen changes on actual provider test-suites.

**Comment by t0yv0** [comment]
There's some additional requirements here I think. @justinvp attempted to pre-test pulumi/pkg changes before they get released through a workflow including upgrade-provider, but the PRs failed for example: 

 https://github.com/pulumi/pulumi-docker/actions/runs/6631589650/job/18015417451 

The workflow tested was https://github.com/pulumi/pulumi-terraform-bridge/actions/workflows/update-providers-test.yml

I think the issue here is that upgrade-provider didn't respect the pre-release pulumi/pkg version that was referenced by the bridge update, thus the builds run into a compilation error.

**Comment by t0yv0** [comment]
@mikhailshilkov @iwahbe can we expedite this? This is hopefully a very small but very impactful change, without this change the bridge reliability initiative that installed https://github.com/pulumi/pulumi-terraform-bridge/actions/workflows/update-providers-test.yml into the bridge release workflows is unable to prevent pulumi/pkg updates from going out ahead of the testing.

**Comment by iwahbe** [comment]
Done. @guineveresaenger added a function to adjust all pkg+sdk references to what `provider/go.mod` uses, so this is just deleting some code.
