### ISSUE TITLE
Make Repo Public

### ISSUE THREAD

**Issue by iwahbe** [pulumi/upgrade-provider#21]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

This is a prerequisite for #12. To do this, we need to 
1. Alter the README to indicate that this tool is intended for internal use only. 
2. Confirm that the company as a whole is ok with making this public.

CC @AaronFriel on (2)

**Comment by AaronFriel** [comment]
I've done this in order to unblock @aq17 and us using the tool via `go install ...`.
