### ISSUE TITLE
Analysis of recent upgrade failures

### ISSUE THREAD

**Issue by t0yv0** [pulumi/upgrade-provider#224]
From ops dashboard on Wed, December 20, 2023. 

```org
|-------+------------------------------------------------------------------------------------------------------------|
| C1    | pull request create failed: GraphQL: Something went wrong while executing your query. Please include `...` |
| C2    | Error .. e/pf@v0.21.0/internal/logging/logging.go:61:11: undefined: logging.NewHost                        |
| C3    | error: error fetching latest Java release exit status 1                                                    |
| C4    | invalid: unknown revision                                                                                  |
| C5    | error: could not determine an upstream version                                                             |
| Flake | Re-running has fixed the problem                                                                           |
```

| C1    | https://github.com/pulumi/pulumi-archive/issues/86      | *Test*
| C1    | https://github.com/pulumi/pulumi-f5bigip/issues/346     |
| C1    | https://github.com/pulumi/pulumi-github/issues/525      |
| C1    | https://github.com/pulumi/pulumi-pagerduty/issues/346   |
| C1    | https://github.com/pulumi/pulumi-signalfx/issues/360    |
| C1    | https://github.com/pulumi/pulumi-splunk/issues/239      |
| C1    | https://github.com/pulumi/pulumi-tailscale/issues/292   |
| C1    | https://github.com/pulumi/pulumi-vault/issues/365       |
| C2    | https://github.com/pulumi/pulumi-aiven/issues/466       |
| C2    | https://github.com/pulumi/pulumi-archive/issues/86      |
| C2    | https://github.com/pulumi/pulumi-artifactory/issues/556 |
| C2    | https://github.com/pulumi/pulumi-cloudflare/issues/598  | *Prod*
| C2    | https://github.com/pulumi/pulumi-datadog/issues/410     |
| C2    | https://github.com/pulumi/pulumi-ec/issues/219          |
| C3    | https://github.com/pulumi/pulumi-gitlab/issues/459      | *Test*
| C4    | https://github.com/pulumi/pulumi-azure/issues/1546      | *Test*
| C4    | https://github.com/pulumi/pulumi-azuread/issues/657     |
| C4    | https://github.com/pulumi/pulumi-gcp/issues/1463        |
| C4    | https://github.com/pulumi/pulumi-random/issues/564      |
| C5    | https://github.com/pulumi/pulumi-okta/issues/484        |  KIND: all, prod?
| Flake | https://github.com/pulumi/pulumi-civo/issues/360        |

**Comment by iwahbe** [comment]
I have manually verified that each of the above issues were fixed in the next bridge release (~30 minutes later), and have closed them.

---

### Context

When I released the bridge, I mistagged `pf/vNext` on the version of the bridge without the upgraded `pf/go.mod` version, causing the bridge update to go out prematurely. I canceled the old workflow, corrected the tag, and pushed (causing a new workflow). The new workflow merged successfully in all cases.
