### ISSUE TITLE
Disable experimental build cache

### ISSUE THREAD

**Issue by iwahbe** [pulumi/upgrade-provider#47]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

https://github.com/pulumi/pulumi-terraform-bridge/pull/1025 introduces an experimental example cache. Until we are 100% sure that the cache is safe (which we are not now), we should disable the cache by setting `PULUMI_CONVERT_EXAMPES_CACHE_DIR=""`.

**Comment by jazzyfresh** [comment]
@aq17 should we add this to the tooling epic?

**Comment by aq17** [comment]
@jazzyfresh done
