### ISSUE TITLE
Update go.mod in examples/

### ISSUE THREAD

**Issue by t0yv0** [pulumi/upgrade-provider#80]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Noting that we might not have it automated to update pkg/ references under examples/. Currently debugging an apparent regression in programtest in pulumi-aws GOOD V3.31.1 <-> BAD V3.63.0. Note how wide the bisect range is. I don't think we update this. [artifactory](https://github.com/pulumi/pulumi-artifactory/blob/main/examples/go.mod#L5) is on v3.17.1

If we do not fix this directly need a way to fix indirectly via dependabot.

**Comment by guineveresaenger** [comment]
Yup, agree this should be addressed.

It's a little bit trickier to do these here. Needs a design doc I think.

**Comment by t0yv0** [comment]
What's the difficulty? On a happy path it's just the same kind of update to examples/go.mod as is done to provider/go.mod.

**Comment by iwahbe** [comment]
This was completed in https://github.com/pulumi/upgrade-provider/commit/b8901aa1bf6bcea8005ea2a0614fee1407aa00d1.
